### create alias
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "add": {
                "alias": "customer",
                "index": "customers"
            }
        },
        {
            "add": {
                "alias": "order",
                "index": "orders"
            }
        }
    ]
}

### switch alias
POST http://localhost:9200/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "remove": {
                "alias": "customer",
                "index": "customers"
            }
        },
        {
            "add": {
                "alias": "customer",
                "index": "customers_v2"
            }
        }
    ]
}

### show aliases
GET  http://localhost:9200/_aliases

### search with alias
GET http://localhost:9200/order/_search