### ---CREATE INDEX---
### create index customers
PUT http://localhost:9200/customers

### create index products
PUT http://localhost:9200/products

### create index orders
PUT http://localhost:9200/orders

### delete index customers
DELETE  http://localhost:9200/customers

### delete index products
DELETE http://localhost:9200/products

### delete index orders
DELETE  http://localhost:9200/orders

### create new customers
POST http://localhost:9200/customers/_create/lamak
Content-Type: application/json

{
    "name": "M Kamaludien A",
    "register_at": "2023-12-22 00:00:00"
}

### create new product
POST http://localhost:9200/products/_create/1
Content-Type: application/json

{
    "name": "Lenovo i3",
    "price": "4500000"
}

### create new / replace product (bisa method PUT juga)
POST http://localhost:9200/products/_doc/4
Content-Type: application/json

{
    "name": "Lenovo i7",
    "price": "6500000"
}

### create new product lagi
POST http://localhost:9200/products/_create/2
Content-Type: application/json

{
    "name": "Samsung M-14",
    "price": 2500000
}

### create new order
POST http://localhost:9200/orders/_create/1
Content-Type: application/json

{
    "order_date": "2023-12-30 00:00:00",
    "customer_id": "lamak",
    "total": "7000000",
    "items": [
        {
            "product_id": 1,
            "price": 4500000,
            "qty": 1
        },
        {
            "product_id": 2,
            "price": 2500000,
            "qty": 1
        }
    ]
}

### update product
POST http://localhost:9200/products/_update/4
Content-Type: application/json

{
    "doc": {
        "price": "7000000"
    }
}

### delete product
DELETE http://localhost:9200/products/_doc/4

### bulk documents
POST http://localhost:9200/_bulk
Content-Type: application/json

< customers-with-banks.json