### get mapping index, url format => http://baseURL/namaIndex/_mapping
GET http://localhost:9200/categories/_mapping

### dynamic mapping / autodetect tipe data
PUT http://localhost:9200/customer/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ],
    "numeric_detection": true
}

### manual mapping
PUT http://localhost:9200/customer/_mapping
Content-Type: application/json

{
    "properties": {
        "username": {
            "type": "keyword"
        },
        "first_name": {
            "type": "text"
        },
        "last_name": {
            "type": "text"
        },
        "email": {
            "type": "keyword"
        },
        "gender": {
            "type": "keyword"
        },
        "birth_date": {
            "type": "date",
            "format": "yyyy-MM-dd"
        }
    }
}

### update manual mapping props in props
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
    "properties": {
        "address": {
            "properties": {
                "street": {
                    "type": "text"
                },
                "city": {
                    "type": "text"
                },
                "province": {
                    "type": "text"
                },
                "country": {
                    "type": "text"
                },
                "zip_code": {
                    "type": "keyword"
                }
            }
        }
    }
}

### update manual mapping (array / array of object mapping)
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
    "properties": {
        "hobbies": {
            "type": "text"
        },
        "banks": {
            "properties": {
                "name" : {
                    "type": "text"
                },
                "account_number" : {
                    "type": "keyword"
                }
            } 
        }
    }
}

### update manual mapping flattened field
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
    "properties": {
        "labels": {
            "type": "flattened"
        }
    }
}

### update manual mapping nested
PUT http://localhost:9200/parents/_mapping
Content-Type: application/json

{
    "properties": {
        "first_name": {
            "type": "text"
        },
        "last_name": {
            "type": "text"
        },
        "children": {
            "type": "nested",
            "properties": {
                "first_name": {
                    "type": "text"
                },
                "last_name": {
                    "type": "text"
                }
            }
        }
    }
}

### multi field mapping
PUT http://localhost:9200/parents/_mapping
Content-Type: application/json

{
    "properties": {
        "fullname": {
            "type": "text",
            "fields": {
                "fn_keyword": {
                    "type": "keyword"
                }
            }
        }
    }
}

### mapping categories
PUT http://localhost:9200/categories/_mapping
Content-Type: application/json

{
    "properties": {
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "text",
            "fields": {
                "raw": {
                    "type": "keyword"
                }
            }
        }
    }
}