### get customer
GET http://localhost:9200/order/_search

### create orders v2
PUT http://localhost:9200/orders_v2

### update orders v2 mapping
PUT http://localhost:9200/orders_v2/_mapping
Content-Type: application/json

{
    "numeric_detection": true,
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}

### reindex order
POST http://localhost:9200/_reindex
Content-Type: application/json

{
    "source" : {
        "index": "orders"
    }, 
    "dest" : {
        "index": "orders_v2"
    }   
}